export const STORAGE_KEYS = {
  JWT: 'pratibha_jwt',
  WORKER_ID: 'pratibha_worker_id',
  WORKER_NAME: 'pratibha_worker_name',
  ANGANWADI_BLOCK: 'pratibha_anganwadi_block',
  MOBILE: 'pratibha_mobile',
  REMEMBER_ME: 'pratibha_remember_me',
  PIN_ENABLED: 'pratibha_pin_enabled',
  PIN_CODE: 'pratibha_pin_code',
  API_MODE: 'pratibha_api_mode',
  GEMINI_KEY: 'pratibha_gemini_key',
  LANGUAGE: 'pratibha_language',
  IS_OFFLINE: 'pratibha_is_offline',
  CHILDREN: 'pratibha_children',
  VISITS: 'pratibha_visits',
  NOTIFICATIONS: 'pratibha_notifications',
  SCHEDULED_ACTIVITIES: 'pratibha_scheduled_activities',
  PENDING_SYNC: 'pratibha_pending_sync',
  CHAT_HISTORY: 'pratibha_chat_history',
  LAST_SYNCED_AT: 'pratibha_last_synced_at',
};
